apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-monkey-config
  labels:
    app: llm-monkey
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/llmmonkey"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
