-- Register PostgreSQL type aliases for H2 compatibility
CREATE DOMAIN IF NOT EXISTS TIMESTAMPTZ AS TIMESTAMP WITH TIME ZONE;
CREATE DOMAIN IF NOT EXISTS JSONB AS TEXT;
CREATE DOMAIN IF NOT EXISTS "text[]" AS TEXT;
CREATE DOMAIN IF NOT EXISTS "uuid" AS UUID;
